# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [ ]:
#code here
import numpy as np

In [ ]:
oArray=np.array([1,2,3,4,5,6,6,7,7,7,7,8])

In [ ]:
reshape=oArray.reshape((3,4))

In [ ]:
print(reshape)

[[1 2 3 4]
 [5 6 6 7]
 [7 7 7 8]]


In [ ]:
a1 = np.array([[1, 2, 3], [7,8,9]])
a2 = np.array([[4, 5, 6], [10, 11, 12]])

In [ ]:
h = np.concatenate((a1, a2), axis=1)
v = np.concatenate((a1, a2), axis=0)

print("Horizontal Concatenation:")
print(h)
print("Vertical Concatenation:")
print(v)

Horizontal Concatenation:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Vertical Concatenation:
[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [ ]:
def classify_emails(emails):
    important_keywords = ["urgent", "hurry", "impo"]
    promotions_keywords = ["discount","sale","deal"]
    spam_keywords = ['prize', 'click here', 'free']

    promotions_emails = []
    spam_emails = []
    important_emails = []

    for email in emails:

        if any(keyword in email.lower() for keyword in important_keywords):
            important_emails.append(email)

        elif any(keyword in email.lower() for keyword in promotions_keywords):
            promotions_emails.append(email)

        elif any(keyword in email.lower() for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails

In [ ]:
# Example usage
sample_emails = [
    "hurry Action Required!",
    "Special Promotion - 50% Off!",
    "Congratulations!free prize!",
    "Meeting agenda for the week",
    "Exclusive deal for our loyal customers"
]

important, promotions, spam = classify_emails(sample_emails)

print("Important Emails:")
print(important)
print()

print("Promotions Emails:")
print(promotions)
print()

print("Spam Emails:")
print(spam)


Important Emails:
['hurry Action Required!']

Promotions Emails:
['Exclusive deal for our loyal customers']

Spam Emails:
['Congratulations!free prize!']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [6]:
# English to Spanish dictionary
english_to_spanish = {
    'how': 'cómo',
    'are': 'están',
    'you': 'tu',
    'hello': 'hola',
    'world': 'mundo',
    'goodbye': 'adiós',
    'cat': 'gato',
    'dog': 'perro',
    'friend': 'amigo',
    'house': 'casa',
    'tree': 'árbol',
    'water': 'agua',
    'sun': 'sol'
}

while True:

    user = input("Enter an English word: ")

    if user == 'exit':
        break

    translate = english_to_spanish.get(user)

    if translate:
        print("The Spanish translation of '{user}' is '{translate}'.")
    else:
        print("Translation not available")

# Inform the user the program is exiting
print("Exiting.....")


Enter an English word: cat
The Spanish translation of 'cat' is 'gato'.
Enter an English word: exit
Exiting.....


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [21]:
import pandas as pd
url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df = pd.read_csv(url)

In [22]:
highest_global_sales_game = df.loc[df['Global_Sales'].idxmax(), 'Name']
print("Game with the Highest Global Sales: {}".format(highest_global_sales_game))


Game with the Highest Global Sales: Wii Sports


In [23]:
# Determine the average sales for each region
average_sales_per_region = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average Sales for Each Region:",average_sales_per_region)

Average Sales for Each Region: NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [24]:
# Find the top 5 most popular game genres based on global sales
top_genres_global_sales = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 Game Genres Based on Global Sales:")
print(top_genres_global_sales)


Top 5 Game Genres Based on Global Sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [26]:
# Calculate total sales for each genre in each region
total_sales_per_genre_per_region = df.groupby(['Genre'])[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
print(total_sales_per_genre_per_region)

              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre                                                  
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36


In [27]:
# Find the most popular genre in North America (NA_Sales)
most_popular_genre_na = total_sales_per_genre_per_region['NA_Sales'].idxmax()
print("Most Popular Genre in North America (NA_Sales): {}".format(most_popular_genre_na))

Most Popular Genre in North America (NA_Sales): Action


In [28]:
# Display last 10 rows
print(df.tail(10))


        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0  

In [29]:

# Determine the top 3 gaming platforms with the highest global sales
top3_platforms_global_sales = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print(top3_platforms_global_sales)

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [30]:
# Calculate the market share for each genre
genre_market_share = (df.groupby('Genre')['Global_Sales'].sum() / total_global_sales) * 100
print(genre_market_share)

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [31]:

# Calculate the correlation coefficient between NA_Sales and EU_Sales
correlation_coefficient = df['NA_Sales'].corr(df['EU_Sales'])
print(correlation_coefficient)

0.7677267483702631


Some tree example

In [20]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
